// SPDX-License-Identifier: AGPL-3.0-only

package engine

import (
	"context"
	"errors"
	"os"
	"time"

	"github.com/jeremiahjrross/podaro/internal/evidence"
	"github.com/jeremiahjrross/podaro/internal/pdr"
	"github.com/jeremiahjrross/podaro/internal/secrets"
	"github.com/jeremiahjrross/podaro/internal/state"
)

// Secrets (API §9): names and metadata only, and the one audited hole.

// SecretView is one row of GET /instances/{name}/secrets: no value.
type SecretView struct {
	Name        string     `json:"name"`
	Kind        string     `json:"kind"`
	Description string     `json:"description,omitempty"`
	DeclaredBy  []string   `json:"declared_by"`
	Created     *time.Time `json:"created,omitempty"`
	Reveals     int        `json:"reveals"`
	// Generated is the kind the value on record was generated as (API §9);
	// absent until a value exists. It differs from Kind only on an
	// authoring instance whose declaration changed after the fact — a
	// state the next create, reconcile, or reset refuses (PDR-E204).
	Generated string `json:"generated,omitempty"`
}

// RemaskAfter is how long the console shows a revealed value (UX §6).
const RemaskAfter = 30 * time.Second

// Secrets lists an instance's secrets: names, kinds, who declared them,
// when they were generated, how often revealed — values are structurally
// absent.
func (e *Engine) Secrets(name string, by Actor) (ret []SecretView, err error) {
	lv, err := e.instanceViewFor(name, by.Gen)
	if err != nil {
		return nil, err
	}
	defer func() { err = e.confirmed(lv, err) }()
	audit, err := e.opts.Store.ListAudit(name)
	if err != nil {
		return nil, storeErr("read the audit stream of "+name, err)
	}
	reveals := map[string]int{}
	for _, a := range audit {
		// This instance's reveals, not the ones a lab that had the name
		// before it earned. The count is smaller than a name, but it is
		// still the previous generation's, and this list is in the
		// attendee's grant (the sibling of round 3's listing, found by asking which other readers reach these rows rather than waiting to be told).
		if a.Seq <= lv.inst.AuditFrom {
			continue
		}
		if a.Action == "reveal" {
			reveals[a.Detail]++
		}
	}
	store := e.secretStore(name)
	out := []SecretView{}
	for _, s := range lv.plan.Secrets {
		v := SecretView{Name: s.Name, Kind: s.Kind, DeclaredBy: s.DeclaredBy, Reveals: reveals[s.Name]}
		if k, err := store.Kind(s.Name); err == nil {
			v.Generated = k
		}
		if fi, err := os.Stat(store.Path(s.Name)); err == nil {
			t := fi.ModTime().UTC()
			v.Created = &t
		}
		if lv.res.Template != nil {
			if d, ok := lv.res.Template.Secrets[s.Name]; ok {
				v.Description = d.Description
			}
		}
		if v.Description == "" && lv.res.Composition != nil {
			for _, m := range lv.res.Composition.Modules {
				if d, ok := m.Module.Secrets[s.Name]; ok {
					v.Description = d.Description
					break
				}
			}
		}
		out = append(out, v)
	}
	return out, nil
}

// Reveal returns a secret's value after appending the audit record (API
// §9: actor, mechanism, timestamp, before responding). A record the
// stream refuses stops the reveal — nothing is revealed unaudited.
func (e *Engine) Reveal(ctx context.Context, name, secret string, by Actor) (ret string, err error) {
	lv, err := e.instanceViewFor(name, by.Gen)
	if err != nil {
		return "", err
	}
	defer func() { err = e.confirmed(lv, err) }()
	declared := false
	for _, s := range lv.plan.Secrets {
		if s.Name == secret {
			declared = true
		}
	}
	if !declared {
		return "", notFoundKind(pdr.CodeSecretNotFound, "secret", secret, "GET /instances/"+name+"/secrets")
	}
	var value string
	// Under the instance guard (guard.go): the value is read and the reveal
	// recorded only for an instance that still exists — never into an
	// evidence directory destroy just removed.
	err = e.withInstance(lv.inst, func() error {
		v, err := e.secretStore(name).Value(secret)
		if errors.Is(err, secrets.ErrNotFound) {
			pe := pdr.New(pdr.CodeSecretNotFound, "secret %s has no value yet", secret)
			pe.Cause = "values are generated by the create job; this instance's has not run its secrets step"
			pe.Next = "podaro up again to resume the create · podaro status " + name
			return pe
		}
		if err != nil {
			return storeErr("read secret "+secret, err)
		}
		now := time.Now().UTC()
		record := state.Audit{At: now, Instance: name, Action: "reveal", Actor: by.Subject, Mechanism: by.Mechanism, Detail: secret}
		if err := e.opts.Store.AppendAudit(record); err != nil {
			return storeErr("audit the reveal of "+secret, err)
		}
		// The evidence journal carries the event too (API §2.5: security
		// events append to the instance evidence stream) — never the value.
		entry := evidence.Entry{Type: evidence.TypeAudit, Instance: name, At: now, Authoring: lv.inst.Mode == state.ModeAuthoring, Audit: &record}
		if _, err := e.journal(name).Append(entry); err != nil {
			e.opts.Logf("%s: evidence: %v", name, err)
		}
		value = v
		return nil
	})
	if err != nil {
		return "", err
	}
	return value, nil
}
